### ISSUE TITLE
Ants VS Bees

### ISSUE THREAD

**Issue by imlored** [sdoro/4D#6]
Riga 208
`min_range = 0`
Riga 209
`max_range = 100`

Problem #3 and #4
> place_to_throw = self.place #Lancio iniziale alla Place in cui si trova la formica stessa
        places_looked = 0

        while place_to_throw is not hive: #Finché la formica non è arrivata all'alveare viene eseguito il ciclo
            if (places_looked >= self.min_range and
                places_looked <= self.max_range):
                bee = random_or_none(place_to_throw.bees) #Ritorna un'ape casuale
                if not bee:
                    place_to_throw = place_to_throw.entrance
                    places_looked +=1 #Incrementa di 1 il Place a cui guarda
                else:
                    return bee #Ritorna un'ape
            else: 
                place_to_throw = place_to_throw.entrance
                places_looked +=1
        
        return None

**Comment by sdoro** [comment]
Perfetto. Ho già aggiornato il file ants.zip e l'ants.py era allineato con l'ultima versione. Faccio commit e chiudo.
