### ISSUE TITLE
problem 4  LongThrower e ShortThrower inserimento caratteristiche

### ISSUE THREAD

**Issue by vangoghdipinto** [sdoro/4D#7]
#LongThrower
implemented = True  
food_cost = 2
min_range = 5
max_range = 100

#ShortThrower
implemented = True   
food_cost = 2
min_range = 0
max_range = 3

**Comment by vidottoalessandro21** [comment]
class LongThrower(ThrowerAnt):    #in questo modo riprende la funzione della thrower ant (con le 
                                                          modifiche sotto) per colpire le api
    name = 'Long'
    food_cost = 2
    min_range = 5
    max_range = 100 

  
class ShortThrower(ThrowerAnt):   
    name = 'Short'
    food_cost = 2
    min_range = 0
    max_range = 3

**Comment by LastHub** [comment]
Riga 241:
```
    food_cost = 2
    min_range = 0
    max_range = 3
```
Dieci righe dopo:```

    food_cost = 2
    min_range = 5
    max_range = 100
```
Altre dieci righe dopo:
```
    food_cost = 6
E implementare il reducing armor
```
Su tutti:`
   implemented = True`

**Comment by sdoro** [comment]
> ```
> food_cost = 6
> ```

food_cost = 2

**Comment by sdoro** [comment]
> #LongThrower
> implemented = True
> food_cost = 2
> min_range = 5
> max_range = 100

max_range non serve sovrascriverlo

> 
> #ShortThrower
> implemented = True
> food_cost = 2
> min_range = 0

min_range non serve sovrascriverlo

> max_range = 3
