### ISSUE TITLE
Problema 4

### ISSUE THREAD

**Issue by LastHub** [sdoro/4D#8]
Riga 241:
```
    food_cost = 2
    min_range = 0
    max_range = 3
```
Dieci righe dopo:```

    food_cost = 2
    min_range = 5
    max_range = 100
```
Altre dieci righe dopo:
```
    food_cost = 6
E implementare il reducing armor
```
Su tutti:`
   implemented = True`

**Comment by sdoro** [comment]
Duplicate of #7
